#!/bin/bash
#Mise à jour des sources et des paquets
apt update -y && apt upgrade -y
#Vérification de Apache
if [ -e /usr/sbin/apache2 ]
then
    echo "Apache n'existe pas"
    echo "Installation"
    apt install -y apache2
    clear
    echo "Apache2 à été installer avec succes"
else
    echo "Apache2 est déja installer"
fi
#Vérification du répertoire site
if [ -e ~/site ]
then
        clear
else
        mkdir site
fi

echo "Veuillez vous assurez que les index ou les fichier soit contenus dans le dossier site"
echo "assurez-vous d'être dans le repértoire de votre utilisateur actuel et de ne pas déposer de dossier dans le dossie>echo "Par exemple si vous effectuer la commande ls dans le dossier site vous ne devez voir que exemple.html et un dossi>read -p "Sont-ils présent ? Y/N : " Choice1
if [ Choice1 -a "Y" ]
then
    read -p "Comment s'appelle votre site : " Nom_site
    echo "copie des fichiers dans le bon repértoire"
    mkdir /var/www/$Nom_site
    cp ~/site/* /var/www/$Nom_site
    cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/$Nom_site.conf
    rm -r ~/site/
else
    echo "ajouter les dans le dossier avant de relancer le script"
    exit
fi

if [ -e /etc/apache2/sites-enable/000-default.conf ]
then
    a2dissite 000-default.conf
fi
a2ensite $Nom_site.conf

#Https

while read -p "Passer le site en HTTPS [Y/N]: " choice2
    do
        case $choice2 in
            Y) break ;;
            N) echo "Bye" ; break ;;
        esac
    done
while read -p "Auto-signer ou let's Encrypt [1 or 2] : " choice3
    do
        case $choice3 in
            1) break ;;
            2) break ;;
        esac
    done
if [ choice3 -eq 1 ]
then
    #installation de openssl
    apt install openssl
    


    
